### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by Reason-pro** [microsoftgraph/msgraph-sample-phpapp#53] opened 2021-02-03 12:54 UTC
Hi! 
I did everything according to the tutorial, but when I try to log in, I get an error:

League\OAuth2\Client\Provider\Exception\IdentityProviderException
invalid_client

![Screenshot 2021-02-03 155339](https://user-images.githubusercontent.com/850059/106749787-0a2f3600-6638-11eb-9673-6befbbe8ccb6.jpg)

**Comment by jasonjoh** [comment] 2021-02-03 13:20
That error usually means there's an issue with the app ID or secret. Can you check that you have your app ID and secret specified in your .env file?

One thing to double-check is that Azure updated their client secret UI, so it doesn't quite match the screenshot in the tutorial. Make sure that you're copying the **Value**, not the **ID**.

![image](https://user-images.githubusercontent.com/8966342/106752623-aa656a80-65f8-11eb-9144-c576134be06e.png)

**Comment by Reason-pro** [comment] 2021-02-03 13:46
Dear Jason!

of course I copied all values

![Screenshot 2021-02-03 164522](https://user-images.githubusercontent.com/850059/106755573-56ca3f80-663f-11eb-83f7-c8ad4051a1ac.jpg)

**Comment by Reason-pro** [comment] 2021-02-03 14:09
now I create new secret and check app id -  not work.
I install new Laravel 
Laravel version 8.26.1
Laravel locale en
Laravel config cached false
PHP version 8.0.1 

did not connect any authorization modules

I can ask a lot of stupid questions this is mine first project using Laravel and there is a chance that I did not connect something

**Comment by jasonjoh** [comment] 2021-02-03 14:17
No problem! I noticed in your screenshot that you may not be using http://localhost:8000? I'm not sure, it's obscured, but it looks like it. When you registered your application, did you set the redirect URI to the same value as you have in your OAUTH_REDIRECT_URI?

**Comment by Reason-pro** [comment] 2021-02-03 14:20
yes, it is my live domain on hosting.
if I change this parameter MSGraph send me error AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'a334c189

**Comment by Reason-pro** [comment] 2021-02-03 14:26
using port 8000 is this required or on a live site not required?

**Comment by Reason-pro** [comment] 2021-02-03 14:38
add port 8000 - it is not work :)

**Comment by jasonjoh** [comment] 2021-02-03 14:49
No it's not required. The only requirement is that the value must match exactly. So on the **Authentication** page in your app registration, the value must match your callback URL.

![image](https://user-images.githubusercontent.com/8966342/106763617-0504c380-6605-11eb-9953-bb35a77d9e00.png)

In your case, you'd replace `http://localhost:8000` with whatever your hosted domain is, but you need to leave the `/callback` piece.

**Comment by Reason-pro** [comment] 2021-02-03 14:52
yes, there are no problems, all paths are spelled out correctly. otherwise, the authorization throws an error and reports that this line does not match

**Comment by jasonjoh** [comment] 2021-02-03 14:55
What do you have on the **Authentication** tab for **Supported account types**?

**Comment by Reason-pro** [comment] 2021-02-03 15:03
multi-tenant Authentication

**Comment by jasonjoh** [comment] 2021-02-03 15:14
Hrmm. On the **Overview** page, under **Endpoints**, what do you have for **OAuth 2.0 authorization endpoint (v2)** and **OAuth 2.0 token endpoint (v2)**?

![image](https://user-images.githubusercontent.com/8966342/106767088-86118a00-6608-11eb-8cd4-477c70cfa6a9.png)

![image](https://user-images.githubusercontent.com/8966342/106767138-9164b580-6608-11eb-8301-9010a8a3a94d.png)

**Comment by Reason-pro** [comment] 2021-02-03 15:34
Yes v2
![image](https://user-images.githubusercontent.com/850059/106769828-71f07b80-664e-11eb-90c7-1c080dec71fa.png)

**Comment by jasonjoh** [comment] 2021-02-03 15:48
Ok, so it seems like configuration is right. You should confirm that the values in your .env file are actually loading. Put this at the top of your `signin` method in AuthController.php.

```
return redirect('/')
  ->with('error', 'App ID from .env')
  ->with('errorDetail', config('azure.appId'));
```

Now when you click the **Sign In** button, it should just redirect back to the home page with the app ID shown in an error box.

![image](https://user-images.githubusercontent.com/8966342/106771808-62047780-660d-11eb-95b4-1626b93714c5.png)

**Comment by Reason-pro** [comment] 2021-02-03 16:43
![image](https://user-images.githubusercontent.com/850059/106779449-0f9c7880-6658-11eb-895b-b5fca0650e40.jpeg)
![image](https://user-images.githubusercontent.com/850059/106779599-33f85500-6658-11eb-9076-11b3363f801e.jpeg)

**Comment by jasonjoh** [comment] 2021-02-03 16:56
Ah ok, you're using a slightly older version of the tutorial, I checked in a fix for #40 that replaced using `env(...)` directly with `config(...)`. See https://github.com/microsoftgraph/msgraph-training-phpapp/blob/main/demo/graph-tutorial/config/azure.php

With the version you're using the debug code should be this instead:

```
return redirect('/')
  ->with('error', 'App ID from .env')
  ->with('errorDetail', env('OAUTH_APP_ID'));
```

But I see that it actually retrieved the value? Did you already make that adjustment?

If you remove that code I had you add, how does the error show up? Is it right after you click **Sign In**, or does your browser redirect to login.microsoftonline.com first? What's the sequence of events?

**Comment by Reason-pro** [comment] 2021-02-03 17:22
I don't know why it worked, I don't make any edits.

I use this tutorial https://docs.microsoft.com/en-us/graph/tutorials/php?tutorial-step=1

![image](https://user-images.githubusercontent.com/850059/106784538-7bcdab00-665d-11eb-98e3-df0cb4f95fdf.jpeg)
![image](https://user-images.githubusercontent.com/850059/106784556-81c38c00-665d-11eb-9609-4f2e613f8139.jpeg)

![image](https://user-images.githubusercontent.com/850059/106784617-93a52f00-665d-11eb-8b58-311d4dd756c2.jpeg)
![image](https://user-images.githubusercontent.com/850059/106784627-97d14c80-665d-11eb-915c-0c792955d4b0.jpeg)

**Comment by jasonjoh** [comment] 2021-02-03 17:42
Ok, that narrows it down a bit. One quick test would be to add double-quotes around your secret value in your .env file, to make sure there isn't an issue with how it's being parsed. Example:

```
OAUTH_APP_SECRET="a;sdkjfl3k4j2l3wkjljslk4322lk3j2l4"
```

If that doesn't fix the problem, what is line 72 in your AuthController.php? The tutorial code has a try/catch that *should* be catching this exception, so I'm not sure why you're getting to this unhandled exception page. It would be helpful to know what the values in the exception are (like `message`, etc.).

**Comment by Reason-pro** [comment] 2021-02-03 18:07
I add double-quotes to .env
![image](https://user-images.githubusercontent.com/850059/106789739-b5091980-6663-11eb-9c55-7f9ad7498907.jpeg)
![image](https://user-images.githubusercontent.com/850059/106789762-bafefa80-6663-11eb-9148-e52b0c397087.jpeg)

![image](https://user-images.githubusercontent.com/850059/106789788-c2be9f00-6663-11eb-96a8-af47b2e7e42b.jpeg)

**Comment by jasonjoh** [comment] 2021-02-03 18:47
Ok. I figured out why it's not catching the exception, there's a missing `\` before `League` in the `catch`.  Anywhere you see `catch (League\`, replace it with `catch (\League`. So that catch on line 87 becomes:

```
catch (\League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) {
```

With that change, the exception should be caught, and the `message` from the exception should get displayed.

**Comment by Reason-pro** [comment] 2021-02-03 19:09
made changes and now a new error

![scr](https://user-images.githubusercontent.com/850059/106796516-8479ad80-666c-11eb-813b-1b4a7d9a89d0.PNG)

**Comment by jasonjoh** [comment] 2021-02-03 19:21
Progress! (of a sort). What I'm really after is the details sent back from the token endpoint along with the error. That *should* tell us why the token endpoint is rejecting your request.

Can you change this line:

```
->with('errorDetail', $e->getMessage());
```

to this:

```
->with('errorDetail', $e->getResponseBody());
```

And see if it reveals anything?

**Comment by Reason-pro** [comment] 2021-02-03 19:24
`catch (\League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) {`
`        return redirect('/')`
`          ->with('error', 'Error requesting access token')`
`          ->with('errorDetail', $e->getResponseBody());`
`      }`

![scr2](https://user-images.githubusercontent.com/850059/106798650-5184e900-666f-11eb-816a-0a1b71654a11.PNG)

`   return htmlspecialchars($value, ENT_QUOTES, 'UTF-8', $doubleEncode);  `

**Comment by jasonjoh** [comment] 2021-02-03 19:41
Sorry! Coding by proxy gets a little tricky! Replace the existing catch with this and hopefully we're there:

```
catch (\League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) {
    $detail = $e->getResponseBody();
    return redirect('/')
        ->with('error', 'Error requesting access token')
        ->with('errorDetail', is_array($detail) ? implode(' ', $detail) : $detail);
}
```

**Comment by Reason-pro** [comment] 2021-02-03 19:49
Sorry, but 

![scr3](https://user-images.githubusercontent.com/850059/106800857-0d471800-6672-11eb-8979-c62ddb5997db.PNG)

**Comment by jasonjoh** [comment] 2021-02-03 19:58
Ok! If you're still with me, replace `implode` with `json_encode`, like so:

```
catch (\League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) {
  return redirect('/')
    ->with('error', 'Error requesting access token')
    ->with('errorDetail', json_encode($e->getResponseBody()));
}
```

**Comment by Reason-pro** [comment] 2021-02-03 20:15
![scr4](https://user-images.githubusercontent.com/850059/106803820-a62b6280-6675-11eb-83a9-bfd3d30b6887.PNG)

**Comment by jasonjoh** [comment] 2021-02-03 20:25
Ok! Took a while but we got it :D.

The error indicates the secret isn't being passed. Not that it's wrong, that it's missing entirely! I'm thinking that you are hitting an issue reading your .env file. So let's see if we can fix that.

1. If you don't already have it, create an azure.php file in the config directory. Find the code [here](https://github.com/microsoftgraph/msgraph-training-phpapp/blob/main/demo/graph-tutorial/config/azure.php).
2. Replace all instances of:

```
'clientId'                => env('OAUTH_APP_ID'),
'redirectUri'             => env('OAUTH_REDIRECT_URI'),
'urlAuthorize'            => env('OAUTH_AUTHORITY').env('OAUTH_AUTHORIZE_ENDPOINT'),
'urlAccessToken'          => env('OAUTH_AUTHORITY').env('OAUTH_TOKEN_ENDPOINT'),
'urlResourceOwnerDetails' => '',
'scopes'                  => env('OAUTH_SCOPES')
```

with:

```
'clientId'                => config('azure.appId'),
'clientSecret'            => config('azure.appSecret'),
'redirectUri'             => config('azure.redirectUri'),
'urlAuthorize'            => config('azure.authority').config('azure.authorizeEndpoint'),
'urlAccessToken'          => config('azure.authority').config('azure.tokenEndpoint'),
'urlResourceOwnerDetails' => '',
'scopes'                  => config('azure.scopes')
```

3. Stop the server, run `php artisan config:clear`, and restart.

If the same error happens after that, confirm that the value isn't being read. Add the following to the top of the `callback` function:

```
return redirect('/')
  ->with('error', 'App secret from .env')
  ->with('errorDetail', config('azure.appSecret'));
```

**Comment by Reason-pro** [comment] 2021-02-03 20:45
![image](https://user-images.githubusercontent.com/850059/106807154-e096fe80-6679-11eb-9d60-d2e725d37a87.png)

![image](https://user-images.githubusercontent.com/850059/106807076-c65d2080-6679-11eb-895f-328315bfd2ed.png)

**Comment by Reason-pro** [comment] 2021-02-03 20:55
I can't figure out how you can easily replace env ('OAUTH_APP_ID') with config ('azure.appId')?  how will he see it if it is not defined anywhere?

**Comment by jasonjoh** [comment] 2021-02-03 20:57
Well to be honest, I've exhausted all I can do to help here. We've verified that the problem is your secret isn't being included in the request, and that this is caused by it not being read from your .env file. You may need to resolve this with your hosting company to figure out why the .env file isn't being read. (Or if you're not using .env on the server and actually setting environment variables, why they aren't being returned).

You might also look at https://linuxhint.com/laravel-is-not-reading-env-file-after-change/ or https://realprogrammer.in/laravel-not-reading-env-file/, they seem to indicate you should run:

```
php artisan config:cache
php artisan config:clear
php artisan cache:clear
```

**Comment by Reason-pro** [comment] 2021-02-03 21:01
Dear Jason!

Thank you for your time and support!  Now I know where to go!  You are the best!

**Comment by jasonjoh** [comment] 2021-02-03 21:07
No problem, I'm just sorry you're still blocked. You did uncover some bugs in my error handling code though so I appreciate it!

**Comment by Reason-pro** [comment] 2021-02-03 21:17
how will I solve the problem I will write here what exactly was

**Comment by Reason-pro** [comment] 2021-02-04 10:56
Dear Jason!

Now it is work, I reinstalled Laravel and put together the project from the very beginning, making all your edits. 

Thank You!

**Comment by jasonjoh** [comment] 2021-02-04 13:00
Thanks for letting me know!

**Closed as completed** 2021-02-04 17:17 UTC
Labels: resolved
