### ISSUE TITLE
Session expiring

### ISSUE THREAD

**Issue by urjuhh** [microsoftgraph/msgraph-sample-phpapp#57] opened 2021-05-15 12:37 UTC
As per @jasonjoh 's suggestion to create a sepparate issue:
After signing in and navigating to calender and then letting it idle for a long time, I was greeted with a

'Undefined index: userTimeZone' in app/Http/Controllers/CalendarController.php
` // Get user's timezone

$timezone = TimeZones::getTzFromWindows($viewData['userTimeZone']);`

After digging around in code and google for some days i came to conclusion ( with my limited know-how in oop and even less in graph / laravel ) that its not an actual issue or bug, but rather a result of something not implemented in the demo (correct me If i'm wrong).

I think replicating the issue should be as simple as deleting cookies from browser that hold the session data to ones demo app.

As for solution i found a suggestion somewhere about creating a Laravel Middleware 'piece' that checks if the token is expired and then act accordingly. 

I do have a workaround that works for me atm, but i dont feel like posting it... I'd rather copy good code than spread something that i'm not sure is safe.
So if a kind soul with the know-how could implement that into the demo

Edit: found the middleware suggestion.... It was the issue #4 from two and a half years ago.... :-/

**Comment by jasonjoh** [comment] 2021-05-17 16:00
Refreshing the token is done in TokenCache.php. I do not reproduce this error with the latest code. I let the app idle for well over an hour and it refreshed the token successfully. Yes I do think that if you delete your session cookie you'll have issues, since all token storage is done in the server-side session. Storing in the session is fine for a sample, but for a production app you'd probably want something more robust, like a secure database, etc.

https://github.com/microsoftgraph/msgraph-training-phpapp/blob/992a95515c151411cb764c57a4edc958f0d7e6ca/demo/graph-tutorial/app/TokenStore/TokenCache.php#L40-L68

**Comment by urjuhh** [comment] 2021-05-17 21:37
Refresh on calendar page on 'clean' instance after 2h 21m idle, same result. 
Dont know how much it changes things that i run the thing on an actual apache server with php7.3.
Same result if i go directly to /calendar without logging in.
Now that should be something thats not implemented to redirect to login and back to /calendar after logging in.
"In real world" you would give someone a link to a certain page, not give em login link and then ask to navigate to required page... But again, thats not a bug. If the purpose of the demo is to show how bits of the sdk work, then it has done its job.
I just wish it had examples of different parts.

God only knows if my modified instance is safe at all... Reloaded page after 11hours and redirected to /signin then to login server that redirected to callback and back to the page i was trying to reload. But then that is how the whole authentication thing should work, if you dont close browser and have the "keep logged in" checked when logging in initially on microsoft page ?

**Comment by jasonjoh** [comment] 2021-05-18 13:16
Because this is a sample, we don't go into any configuration of sessions and just use the defaults from Laravel. I just looked in the session.php file, and this looks interesting:

https://github.com/microsoftgraph/msgraph-training-phpapp/blob/992a95515c151411cb764c57a4edc958f0d7e6ca/demo/graph-tutorial/config/session.php#L23-L34

Auto-login is out of scope for this sample, but redirecting to login should definitely be doable. Something like checking the TokenCache and if it's empty just redirecting to `/signin`.

**Closed as completed** 2021-05-25 19:02 UTC
Labels: needs author feedback, no recent activity
