### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by imprfekt** [microsoftgraph/msgraph-sample-phpapp#54] opened 2021-02-25 17:02 UTC
### Where did you get the code?

- [x] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Downloaded from GitHub
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug
```
League\OAuth2\Client\Provider\Exception\IdentityProviderException
invalid_client
http://localhost:8000/callback?code=M.R3_BAY.4b726340-f363-8457-798b-3b54b282f833&state=6e71605213561ac6f226ac06d5e73219
```
Followed the simple steps as outlined. Tried clearing config and app cache.
Getting the same issue as https://github.com/microsoftgraph/msgraph-training-phpapp/issues/53 and https://github.com/microsoftgraph/msgraph-training-phpapp/issues/6

OR I'm just getting the default home page after the callback. 

### To Reproduce

Follow the steps as outlined in the https://developer.microsoft.com/graph/quick-start

### Expected behavior

I don't know, never got to that point - I suppose I should see a UI showing my calendar.

### Desktop

- OS: OS X
- Browser Chrome
- Version 88

### Dependency versions

Laravel version 7.30.4
PHP version 7.3.24

**Comment by jasonjoh** [comment] 2021-02-25 17:20
@precompiled The only time we've found a root cause for this it was that Laravel was not loading the app's secret from the .env file. (See #53). That person resolved by reinstalling Laravel.

To see if you're having the same issue, can you get the latest code from this repo? It was written with Laravel 8 so it likely wouldn't work with 7.3. If updating isn't an option, can you get a network trace to capture the traffic between your server and login.microsoftonline.com?

**Comment by imprfekt** [comment] 2021-02-25 17:36
Got you the solution.

The `client_secret` (`OAUTH_APP_PASSWORD`) value generated for me (and automatically added to the `.env` file) contained the `#` character (interpreted as a comment), so only portion of that value was passed to the Client constructor, therefore resulting in `invalid_client` error.

Solved it by adding double quotes around it.


Can you, please, modify the "value injection" (i.e. automatically writing values to the `# <OAuthSettingsSnippet>` part of the `.env` file) to add double quotes for values which might contain the `#` character?

Thanks!

**Comment by jasonjoh** [comment] 2021-02-25 18:58
Ah ok - from the quick start downloader. We do have a number of fixes for that in the pipeline but there's some technical issues that have held it up in engineering. Those are solved now so we should be able to get fixes out soon.

**Comment by urjuhh** [comment] 2021-05-08 19:57
I got a similar (or even same) error when i returned to the site after being afk...
After changing all env( "stuff" to config( , and let it sit for a while ( over 2 hours ), I was greeted with a 
'Undefined index: userTimeZone' in app/Http/Controllers/CalendarController.php
`    // Get user's timezone

    $timezone = TimeZones::getTzFromWindows($viewData['userTimeZone']);`


Could it be session expiring and the demo app is not taking it well ?

Edit: got the error when hitting reload while on  /calendar  after long idle time

**Comment by jasonjoh** [comment] 2021-05-10 16:21
@urjuhh would you mind opening a separate issue for this?

**Closed as completed** 2021-05-11 09:47 UTC
Labels: in backlog
